import {
  AlertCircle,
  ArrowRight,
  AtSign,
  Check,
  Eye,
  KeyRound,
  Layers,
  EyeOff,
  LogOut,
  Link2,
  LocateFixed,
  Lock,
  Mail,
  Maximize2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  MapPin,
  Navigation,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Tag,
  Trash2,
  Undo2,
  Wand2,
  X,
} from 'lucide';

export const ICONS = {
  pin: MapPin,
  search: Search,
  submit: ArrowRight,
  plus: Plus,
  refresh: RefreshCw,
  close: X,
  trash: Trash2,
  edit: Pencil,
  play: Play,
  pause: Pause,
  directions: Navigation,
  undo: Undo2,
  collapse: ChevronUp,
  expand: ChevronDown,
  prev: ChevronLeft,
  next: ChevronRight,
  mail: Mail,
  full: Maximize2,
  lock: Lock,
  logout: LogOut,
  link: Link2,
  handle: AtSign,
  alert: AlertCircle,
  eye: Eye,
  layers: Layers,
  // le scene: una cosa premuta, tante che si muovono
  scene: Wand2,
  tag: Tag,
  locate: LocateFixed,
  eyeOff: EyeOff,
  check: Check,
  key: KeyRound,
} as const;

export type IconName = keyof typeof ICONS;
